source 'https://rubygems.org'

gem 'oj', ">=2.13"
gem 'awesome_print'
gem 'allq_rest', '~> 1.2'
gem 'lz4-ruby'
gem 'tty-cursor'
gem 'tty-box'
gem 'tty-command'
gem 'tty-config'
gem 'tty-screen'
gem 'tty-prompt'
gem 'tty-which'
gem 'tty-logger'
gem 'tty-pager'
gem 'tty-pie'
gem 'tty-platform'
gem 'tty-progressbar'
gem 'tty-spinner'
gem 'tty-table'
gem 'tty-tree'
